ERROR - 2025-05-04 04:00:42 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\project_pemweb\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\project_pemweb\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `fo...', 0)
#1 C:\xampp\htdocs\project_pemweb\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fo...')
#2 C:\xampp\htdocs\project_pemweb\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fo...')
#3 C:\xampp\htdocs\project_pemweb\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fo...', Array, false)
#4 C:\xampp\htdocs\project_pemweb\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\project_pemweb\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\project_pemweb\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\project_pemweb\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\project_pemweb\app\Controllers\kontak.php(25): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\project_pemweb\system\CodeIgniter.php(933): App\Controllers\kontak->sendMessage()
#10 C:\xampp\htdocs\project_pemweb\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\kontak))
#11 C:\xampp\htdocs\project_pemweb\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project_pemweb\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\project_pemweb\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\project_pemweb\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\xampp\htdocs\project_pemweb\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-04 04:00:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: kontak/sendMessage]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (:nama:, :email:, :telepon:, :pesan:, :tanggal:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\kontak.php(25): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\kontak->sendMessage()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\kontak))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\project_pemweb\\public\\index.php')
CRITICAL - 2025-05-04 04:00:42 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (\'test\', \'test@gmail.com\', \'085755903155\', \'test\', \'2025-05-04 04:00:41\', \'2025-05-04 04:00:41\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (\'test\', \'test@gmail.com\', \'085755903155\', \'test\', \'2025-05-04 04:00:41\', \'2025-05-04 04:00:41\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (:nama:, :email:, :telepon:, :pesan:, :tanggal:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\kontak.php(25): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\kontak->sendMessage()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\kontak))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\project_pemweb\\public\\index.php')
CRITICAL - 2025-05-04 04:00:42 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (\'test\', \'test@gmail.com\', \'085755903155\', \'test\', \'2025-05-04 04:00:41\', \'2025-05-04 04:00:41\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (\'test\', \'test@gmail.com\', \'085755903155\', \'test\', \'2025-05-04 04:00:41\', \'2025-05-04 04:00:41\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (\'test\', \'test@gmail.com\', \'085755903155\', \'test\', \'2025-05-04 04:00:41\', \'2025-05-04 04:00:41\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (:nama:, :email:, :telepon:, :pesan:, :tanggal:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\kontak.php(25): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\kontak->sendMessage()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\kontak))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\project_pemweb\\public\\index.php')
ERROR - 2025-05-04 04:05:14 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\project_pemweb\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\project_pemweb\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `fo...', 0)
#1 C:\xampp\htdocs\project_pemweb\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fo...')
#2 C:\xampp\htdocs\project_pemweb\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fo...')
#3 C:\xampp\htdocs\project_pemweb\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fo...', Array, false)
#4 C:\xampp\htdocs\project_pemweb\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\project_pemweb\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\project_pemweb\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\project_pemweb\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\project_pemweb\app\Controllers\kontak.php(25): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\project_pemweb\system\CodeIgniter.php(933): App\Controllers\Kontak->sendMessage()
#10 C:\xampp\htdocs\project_pemweb\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Kontak))
#11 C:\xampp\htdocs\project_pemweb\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project_pemweb\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\project_pemweb\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\project_pemweb\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\xampp\htdocs\project_pemweb\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-04 04:05:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: kontak/send]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (:nama:, :email:, :telepon:, :pesan:, :tanggal:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\kontak.php(25): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Kontak->sendMessage()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Kontak))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\project_pemweb\\public\\index.php')
CRITICAL - 2025-05-04 04:05:14 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (\'test\', \'test@gmail.com\', \'085755903155\', \'test\', \'2025-05-04 04:05:14\', \'2025-05-04 04:05:14\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (\'test\', \'test@gmail.com\', \'085755903155\', \'test\', \'2025-05-04 04:05:14\', \'2025-05-04 04:05:14\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (:nama:, :email:, :telepon:, :pesan:, :tanggal:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\kontak.php(25): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Kontak->sendMessage()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Kontak))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\project_pemweb\\public\\index.php')
CRITICAL - 2025-05-04 04:05:14 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (\'test\', \'test@gmail.com\', \'085755903155\', \'test\', \'2025-05-04 04:05:14\', \'2025-05-04 04:05:14\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (\'test\', \'test@gmail.com\', \'085755903155\', \'test\', \'2025-05-04 04:05:14\', \'2025-05-04 04:05:14\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (\'test\', \'test@gmail.com\', \'085755903155\', \'test\', \'2025-05-04 04:05:14\', \'2025-05-04 04:05:14\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (:nama:, :email:, :telepon:, :pesan:, :tanggal:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\kontak.php(25): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Kontak->sendMessage()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Kontak))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\project_pemweb\\public\\index.php')
ERROR - 2025-05-04 06:18:22 --> mysqli_sql_exception: Column 'nama' cannot be null in C:\xampp\htdocs\project_pemweb\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\project_pemweb\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `fo...', 0)
#1 C:\xampp\htdocs\project_pemweb\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fo...')
#2 C:\xampp\htdocs\project_pemweb\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fo...')
#3 C:\xampp\htdocs\project_pemweb\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fo...', Array, false)
#4 C:\xampp\htdocs\project_pemweb\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\project_pemweb\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\project_pemweb\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\project_pemweb\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\project_pemweb\app\Controllers\kontak.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\project_pemweb\system\CodeIgniter.php(933): App\Controllers\Kontak->sendMessage()
#10 C:\xampp\htdocs\project_pemweb\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Kontak))
#11 C:\xampp\htdocs\project_pemweb\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project_pemweb\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\project_pemweb\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\project_pemweb\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\xampp\htdocs\project_pemweb\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-04 06:18:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'nama' cannot be null
[Method: POST, Route: kontak/send]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (:nama:, :email:, :telepon:, :pesan:, :tanggal:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\kontak.php(32): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Kontak->sendMessage()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Kontak))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\project_pemweb\\public\\index.php')
CRITICAL - 2025-05-04 06:18:22 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'nama' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (NULL, \'test@gmail.com\', NULL, NULL, \'2025-05-04 06:18:22\', \'2025-05-04 06:18:22\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (NULL, \'test@gmail.com\', NULL, NULL, \'2025-05-04 06:18:22\', \'2025-05-04 06:18:22\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (:nama:, :email:, :telepon:, :pesan:, :tanggal:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\kontak.php(32): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Kontak->sendMessage()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Kontak))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\project_pemweb\\public\\index.php')
CRITICAL - 2025-05-04 06:18:22 --> [Caused by] mysqli_sql_exception: Column 'nama' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (NULL, \'test@gmail.com\', NULL, NULL, \'2025-05-04 06:18:22\', \'2025-05-04 06:18:22\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (NULL, \'test@gmail.com\', NULL, NULL, \'2025-05-04 06:18:22\', \'2025-05-04 06:18:22\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (NULL, \'test@gmail.com\', NULL, NULL, \'2025-05-04 06:18:22\', \'2025-05-04 06:18:22\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (:nama:, :email:, :telepon:, :pesan:, :tanggal:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\kontak.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Kontak->sendMessage()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Kontak))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\project_pemweb\\public\\index.php')
ERROR - 2025-05-04 06:18:30 --> mysqli_sql_exception: Column 'nama' cannot be null in C:\xampp\htdocs\project_pemweb\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\project_pemweb\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `fo...', 0)
#1 C:\xampp\htdocs\project_pemweb\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fo...')
#2 C:\xampp\htdocs\project_pemweb\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fo...')
#3 C:\xampp\htdocs\project_pemweb\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fo...', Array, false)
#4 C:\xampp\htdocs\project_pemweb\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\project_pemweb\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\project_pemweb\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\project_pemweb\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\project_pemweb\app\Controllers\kontak.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\project_pemweb\system\CodeIgniter.php(933): App\Controllers\Kontak->sendMessage()
#10 C:\xampp\htdocs\project_pemweb\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Kontak))
#11 C:\xampp\htdocs\project_pemweb\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project_pemweb\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\project_pemweb\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\project_pemweb\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\xampp\htdocs\project_pemweb\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-04 06:18:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'nama' cannot be null
[Method: POST, Route: kontak/send]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (:nama:, :email:, :telepon:, :pesan:, :tanggal:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\kontak.php(32): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Kontak->sendMessage()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Kontak))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\project_pemweb\\public\\index.php')
CRITICAL - 2025-05-04 06:18:30 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'nama' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (NULL, \'juan.praka.2405356@students.um.ac.id\', NULL, NULL, \'2025-05-04 06:18:30\', \'2025-05-04 06:18:30\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (NULL, \'juan.praka.2405356@students.um.ac.id\', NULL, NULL, \'2025-05-04 06:18:30\', \'2025-05-04 06:18:30\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (:nama:, :email:, :telepon:, :pesan:, :tanggal:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\kontak.php(32): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Kontak->sendMessage()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Kontak))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\project_pemweb\\public\\index.php')
CRITICAL - 2025-05-04 06:18:30 --> [Caused by] mysqli_sql_exception: Column 'nama' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (NULL, \'juan.praka.2405356@students.um.ac.id\', NULL, NULL, \'2025-05-04 06:18:30\', \'2025-05-04 06:18:30\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (NULL, \'juan.praka.2405356@students.um.ac.id\', NULL, NULL, \'2025-05-04 06:18:30\', \'2025-05-04 06:18:30\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (NULL, \'juan.praka.2405356@students.um.ac.id\', NULL, NULL, \'2025-05-04 06:18:30\', \'2025-05-04 06:18:30\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `form_pesan` (`nama`, `email`, `telepon`, `pesan`, `tanggal`, `updated_at`) VALUES (:nama:, :email:, :telepon:, :pesan:, :tanggal:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\kontak.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Kontak->sendMessage()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Kontak))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\project_pemweb\\public\\index.php')
